// Generated by CoffeeScript 2.3.0
(function() {
  /*
  Virtual touchpad hub class
  */
  var touchpad, virtual_touchpad_hub;

  touchpad = require('./virtual_touchpad');

  virtual_touchpad_hub = class virtual_touchpad_hub {
    constructor() {
      this.touchpads = [];
    }

    connectTouchpad(callback) {
      var touchpadId;
      touchpadId = this.touchpads.length;
      // Create and connect the touchpad
      this.touchpads[touchpadId] = new touchpad();
      return this.touchpads[touchpadId].connect(function() {
        return callback(touchpadId);
      }, function(err) {
        return callback(-1);
      });
    }

    disconnectTouchpad(touchpadId, callback) {
      if (this.touchpads[touchpadId]) {
        return this.touchpads[touchpadId].disconnect(() => {
          this.touchpads[touchpadId] = void 0;
          return callback();
        });
      }
    }

    sendEvent(touchpadId, event) {
      if (this.touchpads[touchpadId]) {
        return this.touchpads[touchpadId].sendEvent(event);
      }
    }

  };

  module.exports = virtual_touchpad_hub;

}).call(this);
